service:
  load_lancer:
    imagem: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./load-balancer/nginx.conf:/etc/nginx/nginx.conf
    
    networks:
      - rede-compose
    depends_on:
      - site1
      - site2

  site1:
    imagem: gabsmvb/culinartfront:latest
    networks: 
      - rede-compose
        driver: bridge
  
  site2:
    imagem: gabsmvb/culinartfront:latest
    networks: 
      - rede-compose
        driver: bridge